
package vista;

import modelo.Cita;
import modelo.CitaDAO;
import javax.swing.table.DefaultTableModel;
import java.util.List;

// Ventana para consultar las citas registradas
public class ConsultarCitas extends javax.swing.JPanel {

   
    public ConsultarCitas() {
        initComponents();
        cargarTabla();
        
        
        tblCitas.setRowHeight(35);
        tblCitas.getColumnModel().getColumn(5).setCellRenderer(new BotonesRenderer());
        tblCitas.getColumnModel().getColumn(5).setCellEditor(new BotonesEditor(tblCitas));
    }
    public void cargarTabla() {

        CitaDAO dao = new CitaDAO();
        List<Cita> lista = dao.listar();

        DefaultTableModel modelo = (DefaultTableModel) tblCitas.getModel();
        modelo.setRowCount(0);

        for (Cita c : lista) {
            Object[] fila = {
                c.getId(),
                c.getNombre(),
                c.getServicio(),
                c.getFecha() + " " + c.getHora(),
                c.getTelefono(),
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        textRegistrar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(212, 175, 55));
        btnBack.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 57, -1, 30));

        textRegistrar.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        textRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        textRegistrar.setText("Consultar citas");
        add(textRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 300, 40));

        jTextField1.setBackground(new java.awt.Color(18, 18, 18));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 175, 55), 1, true));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 55, 200, 35));

        jButton1.setBackground(new java.awt.Color(212, 175, 55));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-búsqueda-20.png"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 55, 40, 35));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));

        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Servicio", "Fecha y hora", "Telefono", "Accion"
            }
        ));
        jScrollPane2.setViewportView(tblCitas);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 730, 450));

        jButton2.setBackground(new java.awt.Color(212, 175, 55));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("2");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 590, 35, 30));

        jButton3.setBackground(new java.awt.Color(212, 175, 55));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("3");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 35, 30));

        jButton4.setBackground(new java.awt.Color(212, 175, 55));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("1");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, 35, 30));

        jLabel1.setBackground(new java.awt.Color(18, 18, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 820X650 SOMBRA.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(810, 650));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 650));
    }// </editor-fold>//GEN-END:initComponents

    // Evento del botón regresar
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);

        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();    
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCitas;
    private javax.swing.JLabel textRegistrar;
    // End of variables declaration//GEN-END:variables
}
