
package vista;

// Clase que gestiona el inicio de sesión del sistema   
public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        textMenu = new javax.swing.JLabel();
        textMenu1 = new javax.swing.JLabel();
        textMenu2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        textMenu3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnInicioSesion = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Legendary Style Inicio de Sesión");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(219, 175, 55));
        Titulo.setFont(new java.awt.Font("Brush Script MT", 1, 42)); // NOI18N
        Titulo.setForeground(new java.awt.Color(212, 175, 55));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Legendary Style");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 280, 45));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 280, 10));

        textMenu.setBackground(new java.awt.Color(255, 255, 255));
        textMenu.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        textMenu.setForeground(new java.awt.Color(180, 180, 180));
        textMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textMenu.setText("Por favor inica sesión para ingreasar");
        jPanel1.add(textMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, -1));

        textMenu1.setBackground(new java.awt.Color(255, 255, 255));
        textMenu1.setFont(new java.awt.Font("sansserif", 1, 32)); // NOI18N
        textMenu1.setForeground(new java.awt.Color(255, 255, 255));
        textMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textMenu1.setText("Inicio de sesión ");
        jPanel1.add(textMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 280, -1));

        textMenu2.setBackground(new java.awt.Color(255, 255, 255));
        textMenu2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        textMenu2.setForeground(new java.awt.Color(255, 255, 255));
        textMenu2.setText("Contraseña");
        jPanel1.add(textMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 315, 130, -1));

        jTextField2.setBackground(new java.awt.Color(18, 18, 18));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Ingrese su contraseña");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 162, 39)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 280, 40));

        textMenu3.setBackground(new java.awt.Color(255, 255, 255));
        textMenu3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        textMenu3.setForeground(new java.awt.Color(255, 255, 255));
        textMenu3.setText("Correo ");
        jPanel1.add(textMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 130, -1));

        jTextField3.setBackground(new java.awt.Color(18, 18, 18));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Ingrese su correo electronico");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(201, 162, 39)));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 255, 280, 40));

        btnInicioSesion.setBackground(new java.awt.Color(219, 175, 55));
        btnInicioSesion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnInicioSesion.setText("Iniciar sesión");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 280, 45));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Recordarme");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 395, 120, 25));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 700X650.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 850, 650));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Evento del botón iniciar sesión
    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel textMenu;
    private javax.swing.JLabel textMenu1;
    private javax.swing.JLabel textMenu2;
    private javax.swing.JLabel textMenu3;
    // End of variables declaration//GEN-END:variables
}
