
package vista;

 import java.awt.BorderLayout; 

// Ventana principal del sistema
public class MenuPrincipal extends javax.swing.JFrame {

  
    public MenuPrincipal() {
        initComponents();
        PanelDerecho.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroung = new javax.swing.JPanel();
        PanelIzquierdo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        textMenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        PerfilAdmin = new javax.swing.JLabel();
        ImgPerfil = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnRegistar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnConfigurar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        PanelDerecho = new javax.swing.JPanel();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        Backgroung.setBackground(new java.awt.Color(0, 0, 0));
        Backgroung.setForeground(new java.awt.Color(0, 0, 0));
        Backgroung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzquierdo.setBackground(new java.awt.Color(18, 18, 18));
        PanelIzquierdo.setMinimumSize(new java.awt.Dimension(290, 650));
        PanelIzquierdo.setPreferredSize(new java.awt.Dimension(290, 650));
        PanelIzquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(219, 175, 55));
        Titulo.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        Titulo.setForeground(new java.awt.Color(212, 175, 55));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Legendary Style");
        PanelIzquierdo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 50));

        textMenu.setBackground(new java.awt.Color(255, 255, 255));
        textMenu.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textMenu.setForeground(new java.awt.Color(255, 255, 255));
        textMenu.setText("Menu ");
        PanelIzquierdo.add(textMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 60, -1));
        PanelIzquierdo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 160, 20));
        PanelIzquierdo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 10));

        PerfilAdmin.setBackground(new java.awt.Color(255, 255, 255));
        PerfilAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PerfilAdmin.setText("Perfil Administrador");
        PanelIzquierdo.add(PerfilAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        ImgPerfil.setBackground(new java.awt.Color(0, 0, 0));
        ImgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-30 (1).png"))); // NOI18N
        PanelIzquierdo.add(ImgPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        lblCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("usuario@email.com");
        PanelIzquierdo.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 130, 40));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        PanelIzquierdo.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 539, -1, 40));

        btnCerrar.setBackground(new java.awt.Color(219, 175, 55));
        btnCerrar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("Cerrar Sesion");
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 160, 40));

        btnRegistar.setBackground(new java.awt.Color(219, 175, 55));
        btnRegistar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRegistar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistar.setText("Registrar Citas");
        btnRegistar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 202, 45));

        btnConsultar.setBackground(new java.awt.Color(219, 175, 55));
        btnConsultar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar Citas");
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 202, 45));

        btnConfigurar.setBackground(new java.awt.Color(219, 175, 55));
        btnConfigurar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnConfigurar.setForeground(new java.awt.Color(0, 0, 0));
        btnConfigurar.setText("Configurar Horarios");
        btnConfigurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(btnConfigurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 202, 45));

        btnReportes.setBackground(new java.awt.Color(219, 175, 55));
        btnReportes.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 0, 0));
        btnReportes.setText("Reportes");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 202, 45));

        btnPerfil.setBackground(new java.awt.Color(219, 175, 55));
        btnPerfil.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setText("Perfil");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 202, 45));

        Backgroung.add(PanelIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 650));

        PanelDerecho.setAlignmentX(0.0F);
        PanelDerecho.setAlignmentY(0.0F);
        PanelDerecho.setMinimumSize(new java.awt.Dimension(810, 650));
        PanelDerecho.setPreferredSize(new java.awt.Dimension(810, 650));
        PanelDerecho.setLayout(new java.awt.BorderLayout());

        ImagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 820X650.png"))); // NOI18N
        ImagenFondo.setText("jLabel2");
        PanelDerecho.add(ImagenFondo, java.awt.BorderLayout.CENTER);

        Backgroung.add(PanelDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 810, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroung, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroung, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Evento del botón cerrar sesion
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        Login login = new Login();
        login.setVisible(true);

        this.dispose(); 

    }//GEN-LAST:event_btnCerrarActionPerformed

    // Evento del botón registrar cita
    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        RegistrarCitas panel = new RegistrarCitas();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();
    }//GEN-LAST:event_btnRegistarActionPerformed

    // Evento del botón consultar cita
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ConsultarCitas panel = new ConsultarCitas();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();        
    }//GEN-LAST:event_btnConsultarActionPerformed

    // Evento del botón configurar horarios
    private void btnConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarActionPerformed
        ConfigHorarios panel = new ConfigHorarios();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();        
    }//GEN-LAST:event_btnConfigurarActionPerformed

    // Evento del botón reportes
    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        Reportes panel = new Reportes();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();  
    }//GEN-LAST:event_btnReportesActionPerformed

    // Evento del botón peril
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        PerfilAdmin panel = new PerfilAdmin();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint(); 
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroung;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel ImgPerfil;
    public static javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelIzquierdo;
    private javax.swing.JLabel PerfilAdmin;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConfigurar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel textMenu;
    // End of variables declaration//GEN-END:variables
}
