
package vista;

 import java.awt.BorderLayout; 


public class MenuPrincipal extends javax.swing.JFrame {

  
    public MenuPrincipal() {
        initComponents();
        PanelDerecho.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroung = new javax.swing.JPanel();
        PanelIzquierdo = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        textMenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        PerfilAdmin = new javax.swing.JLabel();
        ImgPerfil = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        PanelDerecho = new javax.swing.JPanel();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setResizable(false);

        Backgroung.setBackground(new java.awt.Color(0, 0, 0));
        Backgroung.setForeground(new java.awt.Color(0, 0, 0));
        Backgroung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelIzquierdo.setBackground(new java.awt.Color(18, 18, 18));
        PanelIzquierdo.setMinimumSize(new java.awt.Dimension(290, 650));
        PanelIzquierdo.setPreferredSize(new java.awt.Dimension(290, 650));
        PanelIzquierdo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(219, 175, 55));
        Titulo.setFont(new java.awt.Font("Brush Script MT", 1, 32)); // NOI18N
        Titulo.setForeground(new java.awt.Color(212, 175, 55));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Legendary Style");
        PanelIzquierdo.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 50));

        textMenu.setBackground(new java.awt.Color(255, 255, 255));
        textMenu.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textMenu.setForeground(new java.awt.Color(255, 255, 255));
        textMenu.setText("Menu ");
        PanelIzquierdo.add(textMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 60, -1));
        PanelIzquierdo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 160, 20));
        PanelIzquierdo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 10));

        PerfilAdmin.setBackground(new java.awt.Color(255, 255, 255));
        PerfilAdmin.setForeground(new java.awt.Color(255, 255, 255));
        PerfilAdmin.setText("Perfil Administrador");
        PanelIzquierdo.add(PerfilAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        ImgPerfil.setBackground(new java.awt.Color(0, 0, 0));
        ImgPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-test-account-30 (1).png"))); // NOI18N
        PanelIzquierdo.add(ImgPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        lblCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lblCorreo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("usuario@email.com");
        PanelIzquierdo.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 130, 40));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");
        PanelIzquierdo.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 539, -1, 40));

        jButton1.setBackground(new java.awt.Color(219, 175, 55));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cerrar Sesion");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 160, 40));

        jButton2.setBackground(new java.awt.Color(219, 175, 55));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Registrar Citas");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 202, 45));

        jButton3.setBackground(new java.awt.Color(219, 175, 55));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Consultar Citas");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 202, 45));

        jButton4.setBackground(new java.awt.Color(219, 175, 55));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Configurar Horarios");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 202, 45));

        jButton5.setBackground(new java.awt.Color(219, 175, 55));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Reportes");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 202, 45));

        jButton6.setBackground(new java.awt.Color(219, 175, 55));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Perfil");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelIzquierdo.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 202, 45));

        Backgroung.add(PanelIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 650));

        PanelDerecho.setAlignmentX(0.0F);
        PanelDerecho.setAlignmentY(0.0F);
        PanelDerecho.setMinimumSize(new java.awt.Dimension(810, 650));
        PanelDerecho.setPreferredSize(new java.awt.Dimension(810, 650));
        PanelDerecho.setLayout(new java.awt.BorderLayout());

        ImagenFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 820X650.png"))); // NOI18N
        ImagenFondo.setText("jLabel2");
        PanelDerecho.add(ImagenFondo, java.awt.BorderLayout.CENTER);

        Backgroung.add(PanelDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 810, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroung, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backgroung, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login();
        login.setVisible(true);

        this.dispose(); 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RegistrarCitas panel = new RegistrarCitas();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ConsultarCitas panel = new ConsultarCitas();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ConfigHorarios panel = new ConfigHorarios();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Reportes panel = new Reportes();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint();  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PerfilAdmin panel = new PerfilAdmin();

        PanelDerecho.removeAll();
        PanelDerecho.add(panel, BorderLayout.CENTER);

        PanelDerecho.revalidate();
        PanelDerecho.repaint(); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroung;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel ImgPerfil;
    public static javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelIzquierdo;
    private javax.swing.JLabel PerfilAdmin;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel textMenu;
    // End of variables declaration//GEN-END:variables
}
